<a href="https://colab.research.google.com/github/Rufus2711/meta-ad-performance-dashboard/blob/main/NumPy%26pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NumPy**

In [ ]:
import numpy as np         #import syntax

In [ ]:
arr= np.array([1,2,3,4])

In [ ]:
arr*2

array([2, 4, 6, 8])

# **pandas**

**pandas is a library used to work with tables/data.**

Think:

Excel sheets,
SQL tables,
CSV data,
reports.

pandas lets Python handle them efficiently.

MOST IMPORTANT OBJECT IN pandas
**DataFrame**

A DataFrame is basically:

a table.

Very similar to:

Excel table,
SQL result table,
Power BI table.

In [ ]:
import pandas as pd

In [ ]:
data = {
    "Name":["Rufus","Amit","Sara"],
    "Sales":[7000,3000,9000]
}

df=pd.DataFrame(data)
df

    Name  Sales
0  Rufus   7000
1   Amit   3000
2   Sara   9000

In [ ]:
import pandas as pd

data = {
    "Name":["Rufus","Amit","Sara","John"],
    "Sales":[7000,3000,9000,4000],
    "Country":["India","India","USA","India"]
}

In [ ]:
df=pd.DataFrame(data )
df

    Name  Sales Country
0  Rufus   7000   India
1   Amit   3000   India
2   Sara   9000     USA
3   John   4000   India

In [ ]:
df["Sales"]

0    7000
1    3000
2    9000
3    4000
Name: Sales, dtype: int64

In [ ]:
df[df["Country"]=="India"]

    Name  Sales Country
0  Rufus   7000   India
1   Amit   3000   India
3   John   4000   India

In [ ]:
df[df["Sales"]>5000]["Name"]

0    Rufus
2     Sara
Name: Name, dtype: object

In [ ]:

df["Bonus"]=df["Sales"]*0.1

In [ ]:
df["Bonus"]

0    700.0
1    300.0
2    900.0
3    400.0
Name: Bonus, dtype: float64

In [ ]:
df

    Name  Sales Country  Bonus
0  Rufus   7000   India  700.0
1   Amit   3000   India  300.0
2   Sara   9000     USA  900.0
3   John   4000   India  400.0

In [ ]:
df["Performance"]=df["Sales"].apply(
    lambda x: "Excellent" if x>=8000 else "Good" if x>=5000 else "Poor"
)

In [ ]:
df["Performance"]

0         Good
1         Poor
2    Excellent
3         Poor
Name: Performance, dtype: object

In [ ]:
df

    Name  Sales Country  Bonus Performance
0  Rufus   7000   India  700.0        Good
1   Amit   3000   India  300.0        Poor
2   Sara   9000     USA  900.0   Excellent
3   John   4000   India  400.0        Poor

Task

Create a list containing:

customer names ONLY if February sales are greater than 5000.

In [ ]:
data = {
    "customers":[
        {
            "name":"Rufus",
            "orders":{
                "jan":5000,
                "feb":7000
            }
        },
        {
            "name":"Amit",
            "orders":{
                "jan":3000,
                "feb":4000
            }
        }
    ]
}

In [ ]:
data["customers"][0]["orders"]["feb"]

7000

In [ ]:
list1=[]

for customer in data["customers"]:
  if customer["orders"]["feb"]>5000:
    list1.append(customer["name"])

list1

['Rufus']

In [ ]:
list2=[customer["name"] for customer in data["customers"] if customer["orders"]["feb"]>5000]
list2

['Rufus']

Task

Find:

total February sales

In [ ]:
total_sales=0

for customer in data["customers"]:
    total_sales=total_sales+customer["orders"]["feb"]

In [ ]:
total_sales

11000

Task

Display:

ONLY names
where:
Country is "India"
AND Sales > 5000

In [ ]:
import pandas as pd

data = {
    "Name":["Rufus","Amit","Sara","John"],
    "Sales":[7000,3000,9000,4000],
    "Country":["India","India","USA","India"]
}

In [ ]:
df=pd.DataFrame(data)

In [ ]:
df[(df["Country"]=="India") & (df["Sales"]>5000)]["Name"]

0    Rufus
Name: Name, dtype: object

Task

Create a list containing:

customer names
ONLY if:
January + February sales combined are greater than 12000

In [ ]:
data = {
    "customers":[
        {
            "name":"Rufus",
            "orders":{"jan":5000,"feb":7000}
        },
        {
            "name":"Amit",
            "orders":{"jan":3000,"feb":4000}
        },
        {
            "name":"Sara",
            "orders":{"jan":8000,"feb":9000}
        }
    ]
}

In [ ]:
list1=[customer["name"] for customer in data["customers"] if customer["orders"]["jan"]+customer["orders"]["feb"]>12000]

list1

['Sara']

In [ ]:
list2=[]

for customer in data["customers"]:
  if customer["orders"]["jan"]+customer["orders"]["feb"]>12000:
    list2.append(customer["name"])

list2

['Sara']

pandas Multi-Condition Filtering

Display ONLY names where:

Country is India
AND
Sales > 5000
OR
Experience >= 5

In [ ]:
import pandas as pd

data = {
    "Name":["Rufus","Amit","Sara","John"],
    "Sales":[7000,3000,9000,4000],
    "Country":["India","India","USA","India"],
    "Experience":[3,1,5,2]
}

df=pd.DataFrame(data)

df[((df["Country"]=="India") & (df["Sales"]>5000)) | (df["Experience"]>=5)]["Name"]

0    Rufus
2     Sara
Name: Name, dtype: object

Task

Create new column:Level


Rules:

Sales >= 8000 → "Senior"
Sales >= 5000 → "Mid"
otherwise → "Junior"

Use:

apply()
lambda

In [ ]:
df["Level"]=df["Sales"].apply (
    lambda x: "Senior" if x >=8000
    else "Mid" if x>=5000 else "Junior"
)

df["Level"]

0       Mid
1    Junior
2    Senior
3    Junior
Name: Level, dtype: object

In [ ]:
df

    Name  Sales Country  Experience   Level
0  Rufus   7000   India           3     Mid
1   Amit   3000   India           1  Junior
2   Sara   9000     USA           5  Senior
3   John   4000   India           2  Junior

Task

Find:

total Sales ONLY for customers from India.

In [ ]:
import pandas as pd

data = {
    "Name":["Rufus","Amit","Sara","John"],
    "Sales":[7000,3000,9000,4000],
    "Country":["India","India","USA","India"],
    "Experience":[3,1,5,2]
}

df=pd.DataFrame(data)

df

    Name  Sales Country  Experience
0  Rufus   7000   India           3
1   Amit   3000   India           1
2   Sara   9000     USA           5
3   John   4000   India           2

In [ ]:
df1=df[df["Country"]== "India"]
df1

    Name  Sales Country  Experience
0  Rufus   7000   India           3
1   Amit   3000   India           1
3   John   4000   India           2

In [ ]:
total_sales=df1["Sales"].sum()

total_sales

np.int64(14000)

# **DataFrame Inspection**

In [ ]:
import pandas as pd

data= [
  {
    "Name": "Rufus",
    "Country": "India",
    "Department": "Sales",
    "Sales": 7000,
    "Age": 26
  },
  {
    "Name": "Amit",
    "Country": "India",
    "Department": "HR",
    "Sales": 4000,
    "Age": 31
  },
  {
    "Name": "Sara",
    "Country": "USA",
    "Department": "Sales",
    "Sales": 9000,
    "Age": 29
  },
  {
    "Name": "Neha",
    "Country": "India",
    "Department": "Tech",
    "Sales": 8500,
    "Age": 27
  },
  {
    "Name": "John",
    "Country": "USA",
    "Department": "Tech",
    "Sales": 3000,
    "Age": 35
  },
  {
    "Name": "Priya",
    "Country": "India",
    "Department": "Sales",
    "Sales": 6500,
    "Age": 24
  },
  {
    "Name": "David",
    "Country": "Canada",
    "Department": "HR",
    "Sales": 5000,
    "Age": 32
  },
  {
    "Name": "Ankit",
    "Country": "India",
    "Department": "Tech",
    "Sales": 7200,
    "Age": 28
  }
]

df=pd.DataFrame(data)

df

    Name Country Department  Sales  Age
0  Rufus   India      Sales   7000   26
1   Amit   India         HR   4000   31
2   Sara     USA      Sales   9000   29
3   Neha   India       Tech   8500   27
4   John     USA       Tech   3000   35
5  Priya   India      Sales   6500   24
6  David  Canada         HR   5000   32
7  Ankit   India       Tech   7200   28

Task

Show employees who:

belong to India
AND have Sales greater than 5000

In [ ]:
df[(df["Country"]== "India") & (df["Sales"]>5000)]

    Name Country Department  Sales  Age
0  Rufus   India      Sales   7000   26
3   Neha   India       Tech   8500   27
5  Priya   India      Sales   6500   24
7  Ankit   India       Tech   7200   28

Next Task — Column Selection After Filtering

Goal:

Show ONLY the Name and Sales columns for employees:

from India
whose Sales are greater than 5000

In [ ]:
df[(df["Country"]== "India") & (df["Sales"]>5000)][["Name","Sales"]]

    Name  Sales
0  Rufus   7000
3   Neha   8500
5  Priya   6500
7  Ankit   7200

Task — Sorting After Filtering

Now let’s chain another operation.

Goal:

Show:

employees from India
with Sales greater than 5000
displaying only Name and Sales
sorted from highest Sales to lowest

In [ ]:
tab1=df[(df["Country"]== "India") & (df["Sales"]>5000)][["Name","Sales"]].sort_values("Sales",ascending=False)

In [ ]:
tab1

    Name  Sales
3   Neha   8500
7  Ankit   7200
0  Rufus   7000
5  Priya   6500

Task — Aggregation After Filtering

Now let’s move into:

filter → aggregate workflows

In [ ]:
avg_sal=df[df["Country"]=="India"]["Sales"].mean()
avg_sal

np.float64(6640.0)

Goal

Find:

how many employees belong to each Department

In [ ]:
tab2=df["Department"].value_counts()
tab2

Department
Sales    3
Tech     3
HR       2
Name: count, dtype: int64

# **Null Handling**

In [ ]:
import pandas as pd

data2 = [
    {"Name": "Rufus", "Country": "India", "Sales": 7000},
    {"Name": "Amit", "Country": None, "Sales": 4000},
    {"Name": "Sara", "Country": "USA", "Sales": None},
    {"Name": "Neha", "Country": "India", "Sales": 8500}
]

df2=pd.DataFrame(data2)

df2

    Name Country   Sales
0  Rufus   India  7000.0
1   Amit    None  4000.0
2   Sara     USA     NaN
3   Neha   India  8500.0

task:

Use a pandas operation to:

detect missing values

In [ ]:
df2.isnull()

    Name  Country  Sales
0  False    False  False
1  False     True  False
2  False    False   True
3  False    False  False

In [ ]:
df2.isnull().sum()

Name       0
Country    1
Sales      1
dtype: int64

In [ ]:
df2.fillna(0)

    Name Country   Sales
0  Rufus   India  7000.0
1   Amit       0  4000.0
2   Sara     USA     0.0
3   Neha   India  8500.0

In [ ]:
df2

    Name Country   Sales
0  Rufus   India  7000.0
1   Amit    None  4000.0
2   Sara     USA     NaN
3   Neha   India  8500.0

In [ ]:
df2["Sales"].fillna(0)

0    7000.0
1    4000.0
2       0.0
3    8500.0
Name: Sales, dtype: float64

In [ ]:
df2[df2["Sales"].isnull()]

   Name Country  Sales
2  Sara     USA    NaN

# **Duplicates**

In [ ]:
import pandas as pd

data3=[
    {"Name": "Rufus", "Country": "India"},
    {"Name": "Amit", "Country": "India"},
    {"Name": "Rufus", "Country": "India"},
    {"Name": "Sara", "Country": "USA"}
]

df3=pd.DataFrame(data3)

df3

    Name Country
0  Rufus   India
1   Amit   India
2  Rufus   India
3   Sara     USA

In [ ]:
df3.duplicated()

0    False
1    False
2     True
3    False
dtype: bool

In [ ]:
df3.drop_duplicates()

    Name Country
0  Rufus   India
1   Amit   India
3   Sara     USA

In [ ]:
df

    Name Country Department  Sales  Age
0  Rufus   India      Sales   7000   26
1   Amit   India         HR   4000   31
2   Sara     USA      Sales   9000   29
3   Neha   India       Tech   8500   27
4   John     USA       Tech   3000   35
5  Priya   India      Sales   6500   24
6  David  Canada         HR   5000   32
7  Ankit   India       Tech   7200   28

Task For Today

Using your original employee dataframe (df):

Write a workflow that:

shows ONLY employees from India
selects:
Name
Department
Sales
sorts highest Sales first

In [ ]:
tab5=df[df["Country"]=="India"][["Name","Department","Sales"]].sort_values("Sales",ascending=False)
tab5

    Name Department  Sales
3   Neha       Tech   8500
7  Ankit       Tech   7200
0  Rufus      Sales   7000
5  Priya      Sales   6500
1   Amit         HR   4000

In [ ]:
df

    Name Country Department  Sales  Age
0  Rufus   India      Sales   7000   26
1   Amit   India         HR   4000   31
2   Sara     USA      Sales   9000   29
3   Neha   India       Tech   8500   27
4   John     USA       Tech   3000   35
5  Priya   India      Sales   6500   24
6  David  Canada         HR   5000   32
7  Ankit   India       Tech   7200   28

Task 1 — Filtering + Selection

Show:

employees from USA

Display ONLY:

Name
Sales

In [ ]:
usa_sales=df[df["Country"]=="USA"][["Name","Sales"]]
usa_sales

   Name  Sales
2  Sara   9000
4  John   3000

Task 2 — Filtering + Aggregation

Find:

average Sales of employees from Tech department

In [ ]:
avg_tech_sales=df[df["Department"]=="Tech"]["Sales"].mean()
round(avg_tech_sales,2)

np.float64(6233.33)

Task 3 — Null Detection + Filtering

Show ONLY rows where:

Sales is missing

In [ ]:
import pandas as pd

data4 = [
    {"Name":"Rufus","Sales":7000},
    {"Name":"Amit","Sales":None},
    {"Name":"Sara","Sales":9000},
    {"Name":"Neha","Sales":None}
]

df4=pd.DataFrame(data4)

df4

    Name   Sales
0  Rufus  7000.0
1   Amit     NaN
2   Sara  9000.0
3   Neha     NaN

In [ ]:
missing_sales=df4[df4["Sales"].isnull()]
missing_sales

   Name  Sales
1  Amit    NaN
3  Neha    NaN

Task 1 — Multi-Step Workflow

Create a dataframe that:

keeps ONLY India employees
removes rows where Sales is missing
displays ONLY:
Name
Department
Sales
sorts highest Sales first

In [ ]:
import pandas as pd

data6 = [
    {"Name":"Rufus","Country":"India","Department":"Sales","Sales":7000},
    {"Name":"Amit","Country":"India","Department":"HR","Sales":None},
    {"Name":"Sara","Country":"USA","Department":"Sales","Sales":9000},
    {"Name":"Neha","Country":"India","Department":"Tech","Sales":8500},
    {"Name":"John","Country":"USA","Department":"Tech","Sales":3000},
    {"Name":"Priya","Country":"India","Department":"Sales","Sales":6500}
]

df5=pd.DataFrame(data6)

df5

    Name Country Department   Sales
0  Rufus   India      Sales  7000.0
1   Amit   India         HR     NaN
2   Sara     USA      Sales  9000.0
3   Neha   India       Tech  8500.0
4   John     USA       Tech  3000.0
5  Priya   India      Sales  6500.0

In [ ]:
india_report=df5[df5["Country"]=="India"].dropna(subset=["Sales"])[["Name","Department","Sales"]].sort_values("Sales",ascending=False)

india_report

    Name Department   Sales
3   Neha       Tech  8500.0
0  Rufus      Sales  7000.0
5  Priya      Sales  6500.0

Final Challenge

Using df6:

Create a dataframe that:

keeps ONLY employees from:
India
OR USA
removes rows where Sales is missing
keeps ONLY:
Name
Country
Sales
sorts by Sales highest to lowest
stores result in: final_report

In [ ]:
df5

    Name Country Department   Sales
0  Rufus   India      Sales  7000.0
1   Amit   India         HR     NaN
2   Sara     USA      Sales  9000.0
3   Neha   India       Tech  8500.0
4   John     USA       Tech  3000.0
5  Priya   India      Sales  6500.0

In [ ]:
final_report= (
    df5[
    (df5["Country"]=="India") |
    (df5["Country"]=="USA")
]
    .dropna(subset=["Sales"])
[["Name","Country","Sales"]]
    .sort_values("Sales",ascending=False)
    )

final_report

    Name Country   Sales
2   Sara     USA  9000.0
3   Neha   India  8500.0
0  Rufus   India  7000.0
5  Priya   India  6500.0
4   John     USA  3000.0